[build]
target = "riscv32imc-unknown-none-elf"

[target."riscv32imc-unknown-none-elf"]
runner = "wlink -v flash --enable-sdi-print --watch-serial --erase"
# runner = "probe-rs run --chip ch32v203"
# runner = "arm-none-eabi-size"
# runner = "riscv64-unknown-elf-size"
# Manual: "riscv64-unknown-elf-size target/riscv32imc-unknown-none-elf/release/ch32v203"
# "cargo size --release" does not work unfortunately